### ISSUE TITLE
When server crashes/fails to run because it can't allocate enough ram, Nihilus crashes.

### ISSUE THREAD

**Issue by anthonymendez** [ForkGG/fork#1]
Noticed this behavior first time creating and launching a world. The bug is on line 24 of this set of notes.

[2020_1_5_v0_5_notes_AM.txt](https://github.com/ChristianKern97/nihilus/files/4565008/2020_1_5_v0_5_notes_AM.txt)

Behavior:
So the default settings for the memory allocations have it allocating a maximum amount of 2 Gb of ram. No problem with this just happens my laptop has an issue with this for some reason (more than enough ram available). This, of course, causes the server to crash. Expected, but then it also crashes Nihilus with it. This shouldn't happen IMO.

System Info:
Intel Core i5-7300HQ
16 Gb of DDR3 @ 2400 Mhz
GTX 1050

**Comment by ChristianKern97** [comment]
I can't reproduce the issue, because the cause is probably not the ram usage.

The server runs in it's own java process and if it crashes it wouldn't impact the Nihilus.exe process. 
Now that there is error logging it is probably easier to find the root cause.

**Comment by anthonymendez** [comment]
Re-ran on my laptop with 0.5.1.

[consoleLog.txt](https://github.com/ChristianKern97/nihilus/files/4569377/consoleLog.txt)

errorLog.txt came out empty.

**Comment by ChristianKern97** [comment]
Can you try to reproduce this again on the current version?
