### ISSUE TITLE
Not allowing me to create or import a spigot, or bungee server

### ISSUE THREAD

**Issue by MrSpaceCarrot** [ForkGG/fork#12]
When I try to import or create a vanilla server, it's fine. But when I click on some other server type, nothing happens. Hope this gets fixed, because this looks like such a great project! 

EDIT: nvm, just realised that support is coming, said it was already implemented on the website tho

**Comment by ChristianKern97** [comment]
While you are right, this should not be on the website yet, spigot and paper aswell as bungee and waterfall are basically the same with minor differences. If you got a spigot server just import it as a paper server and it should work all fine.
