### ISSUE TITLE
Application interface freezes after a certain number of lines of console text.

### ISSUE THREAD

**Issue by trenton-telge** [ForkGG/fork#15]
The program Fork.exe version 0.7.5.3 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 54d0
 Start Time: 01d6d6204c942dc3
 Termination Time: 5
 Application Path: C:\Program Files\Fork.exe
 Report Id: 88cb0af2-9bd8-42ee-b38f-3ddf0329da1e
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown

![image](https://user-images.githubusercontent.com/5915803/102919380-5f2f3800-444e-11eb-8d05-6d8157e32fad.png)

Problem signature
Problem Event Name:	AppHangB1
Application Name:	Fork.exe
Application Version:	0.7.5.3
Application Timestamp:	5f3ed60d
Hang Signature:	071f
Hang Type:	134217728
OS Version:	10.0.19042.2.0.0.768.101
Locale ID:	1033
Additional Hang Signature 1:	071f8f829b01f11e4c5d6ddb54741e3e
Additional Hang Signature 2:	6c90
Additional Hang Signature 3:	6c906b4c19d1bdaffcfde8bc984091ba
Additional Hang Signature 4:	071f
Additional Hang Signature 5:	071f8f829b01f11e4c5d6ddb54741e3e
Additional Hang Signature 6:	6c90
Additional Hang Signature 7:	6c906b4c19d1bdaffcfde8bc984091ba

Extra information about the problem
Bucket ID:	5d58ac57252409152ca87b73618c59ea (2065036164637415914)

**Comment by ChristianKern97** [comment]
Sadly I can’t use any of the given information   

Are there any logs at: %appdata%/Fork/logs?

**Comment by trenton-telge** [comment]
[errorLog.txt](https://github.com/ForkGG/fork/files/5731416/errorLog.txt)

**Comment by ChristianKern97** [comment]
Do you have java installed?

**Comment by trenton-telge** [comment]
Yes, my active version is 13.0.2

![image](https://user-images.githubusercontent.com/5915803/102920448-69523600-4450-11eb-8729-7a325f6cfc92.png)

**Comment by trenton-telge** [comment]
I have noted this error in Java versions 8.121 and 11.0.7 as well. Been fighting this crash on and off for two weeks. Happens every 48 hours or so.

**Comment by ChristianKern97** [comment]
Ok so it does not happen after any certain action?

**Comment by trenton-telge** [comment]
No, it happens completely randomly. It's happened during server startup, and it's happened during hours of idling. The only thing I can think of is that it seems to stop text from appearing in the GUI console, so it may be related to that. The server itself continues to function without lag, it's just Fork that freezes.

**Comment by ChristianKern97** [comment]
Ah ok i know what the issue is. I already fixed it i think and will release a new update later

**Comment by trenton-telge** [comment]
Alright, looking forward to it!

**Comment by ChristianKern97** [comment]
Alright the update just got released. Try if it works and let me know

**Comment by trenton-telge** [comment]
The server's been up on the new version for 2 days and no crashes, so it appears to have fixed my issue :smile:
