### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Petrosado** [ForkGG/fork#16]
After adding the first server to the list it crashed and then continuosly crashed on startup ill get to the UI but even if i dont press anything it crashes

**Comment by ChristianKern97** [comment]
Can you send the errorlog from %appdata%/Fork/logs

Also make sure you use the latest version (0.7.6)

**Comment by Petrosado** [comment]
[errorLog.txt](https://github.com/ForkGG/fork/files/5739316/errorLog.txt)
Here

**Comment by ChristianKern97** [comment]
One possible fix is to delete the folder: %AppData%/Fork/players

**Comment by Petrosado** [comment]
> One possible fix is to delete the folder: %AppData%/Fork/players

Wont it delete everyones inventory?

**Comment by ChristianKern97** [comment]
No that are just the cached player informations for fork

**Comment by Petrosado** [comment]
> No that are just the cached player informations for fork

Still crashed

**Comment by ChristianKern97** [comment]
Still the same error in the erro log?

**Comment by Petrosado** [comment]
> Still the same error in the erro log?

[errorLog.txt](https://github.com/ForkGG/fork/files/5739634/errorLog.txt)

**Comment by ChristianKern97** [comment]
Ok have you tried reinstalling fork, by deleting the whole fork folder? But make sure to save the server files somewhere

**Comment by Petrosado** [comment]
> Ok have you tried reinstalling fork, by deleting the whole fork folder? But make sure to save the server files somewhere
I cant reinstall it because wen i try to delete it it says "The action can't be completed because the filse is open in System"

**Comment by ChristianKern97** [comment]
Open the Task manager and look for java.exe and fork.exe tasks

**Comment by Petrosado** [comment]
> Open the Task manager and look for java.exe and fork.exe tasks

Still crases even after reinstalling

**Comment by ChristianKern97** [comment]
Are you importing a server or creating a nwe one?

**Comment by Petrosado** [comment]
> Are you importing a server or creating a nwe one?

Importing

**Comment by ChristianKern97** [comment]
Can you send me the server files you try to import, or do they contain any sensitive information?

**Comment by Petrosado** [comment]
> Can you send me the server files you try to import, or do they contain any sensitive information?

The world file is half a gigabyte so i dont think i can send it

**Comment by Petrosado** [comment]
https://www.mediafire.com/file/mwcmqxkrpcdu0by/Server.rar/file

**Comment by ChristianKern97** [comment]
Ok i can't figure out the problem right now sorry, i will debug it later, but today is kinda stressful sorry

**Comment by Petrosado** [comment]
> Ok i can't figure out the problem right now sorry, i will debug it later, but today is kinda stressful sorry

Its alright i hope youll have a nice day

**Comment by ChristianKern97** [comment]
Ok i found the source of the issue:
The `whitelist.json` contains a player with the name set to `60e6c610-ab30-3f4e-9c48-fe18da605f68` which is invalid and mojang API returns a `400 Bad Request` which is not handled by Fork

Quick Fix: Delete that entry from the `whitelist.json` file (It is probably invalid anyway)

I will patch this issue with the next update. Thanks for reporting

**Comment by Petrosado** [comment]
> Ok i found the source of the issue:
> The `whitelist.json` contains a player with the name set to `60e6c610-ab30-3f4e-9c48-fe18da605f68` which is invalid and mojang API returns a `400 Bad Request` which is not handled by Fork
> 
> Quick Fix: Delete that entry from the `whitelist.json` file (It is probably invalid anyway)
> 
> I will patch this issue with the next update. Thanks for reporting

thank you It worked! but i had to also remove it from the playerdata file
