### ISSUE TITLE
Crashes on starting two servers under bungee.

### ISSUE THREAD

**Issue by itoncek4** [ForkGG/fork#17]
Simply add two servers under one bungee, and set "Start servers with proxy". Applicaton crashes after three seconds, but servers keep running.

**Comment by ChristianKern97** [comment]
Can you send the errorLog from %appdata%/Fork/logs?

**Comment by ChristianKern97** [comment]
As no further information was given i will close this issue for now. If this bug still exists let me know and we open it again
